name=LCDKnightI2C
version=1.0.0
author=Gopi Ragul R
maintainer=Gopi Ragul R
sentence=Ultra simple I2C LCD library for beginners.
paragraph=LCDKnightI2C is a lightweight plug-and-play LCD library with simplified commands for Arduino projects.
category=Display
url=https://github.com/
architectures=*